### ISSUE TITLE
Streamline Notification Flow

### ISSUE THREAD

**Issue by BajajGirik** [BajajGirik/deal-finder#10]
## Overview:
It's a continuation of https://github.com/BajajGirik/deal-finder/issues/2.
Since we have two notification services now (discord and email), I think we should just encapsulate it under one module and refactor the code.\
This module will contain a `Notification` class which will have `DiscordNotification` class and `EmailNotification` class as it's attributes.\
This way one can directly use the `Notification` class and call the required method

## Basic File Structure:
In the notification folder, we will have 4 files for now.
```
notification
├── __init__.py
├── discord.py
├── email.py
└── notification.py
```
The `discord.py` already exists and just needs to be moved to the notification folder which will be created in the linked issue.

**Comment by BajajGirik** [comment]
@PhoenixOutlaw If you wish, you can make the changes in your current PR you are working on.

**Comment by Antiarin** [comment]
I'm taking over this issue. 😘

**Comment by BajajGirik** [comment]
Too much time taken on this simple issue. I'll handle it now.
